@startuml

skinparam componentStyle rectangle

package "Database Before Operation" as DBO {
  [Table1] as table1_1
  [Table2] as table2_1
}

table2_1 -[hidden]> table1_1

package "Database After Operation" as DAO {
  [flyway_schema_history] as fsh_2
  [Table1] as table1_2
  [Table2] as table2_2
}

fsh_2 -[hidden]-> table1_2
table2_2 -[hidden]> table1_2

package "flyway baseline" as OP {
}

table1_1 -[hidden]> OP
OP -[hidden]-> DAO

DBO -> OP
OP -> DAO

note left of fsh_2: Created by Operation

@enduml